// Every user-visible string lives here (spec V1), so a word can be renamed in one place as the vocabulary settles.
export const STR = {
  snap: {
    corner: 'tile corner',
    edge: 'tile edge',
    axis: 'mirror axis',
    impliedAxis: 'mirror axis (stacked groups)',
    centre: (n: number) => `rotation point (1/${n})`,
    cross: (a: string, b: string) => `${a} × ${b}`,
    node: 'node',
    cloneNode: 'node of a clone',
    line: 'line',
    cloneLine: 'line of a clone',
    ownLine: 'this line',
    ownStart: 'this line\'s start',
    cloneStart: 'its clone\'s start',
    repeatStart: 'its repeat\'s start',
    ownCloneLine: 'its clone',
    ownRepeatLine: 'its repeat',
    meetsMirror: 'meets its mirror clone',
    meetsRotated: 'meets its rotated clone',
    meetsOwn: 'meets its own copy',
    meetsCloneEnd: "meets its clone's end",
    meetsCloneEndLine: "meets its clone's end",
    meetsMirrorCopy: 'meets its mirror copy',
    meetsRotatedCopy: 'meets its rotated copy',
    meetsCopyEnd: "meets its copy's end",
    grid: 'grid',
    guide: 'guide',
    traced: 'traced line',
  },
  hint: {
    rotate: 'Rotation: drag to move · pick 1/2, 1/3, 1/4 or 1/6 · clones turn about it · O on a selected path stacks it as a new group',
    mirror: 'Mirror: drag to move · knob or [ ] rotates · put a translation after it in a chain for a glide',
    translate: 'Translation: drag the diamond to set the vector · snaps to quarters, thirds and halves of the tile · hold ⌘ or Ctrl for any length',
    construction: 'Construction layer: add or drag elements and lattice handles · the drawing is locked · Tab to go back',
    points: (n: number) => `${n} point${n > 1 ? 's' : ''} selected · drag to move together · ⇧-click adds · ⌫ deletes`,
    instances: (n: number) => `${n} instances · ⌫ deletes their paths`,
    clone: 'Clone: drag its body to move the first element of its first group · drag its anchors to edit the shared shape · drag an anchor on a shared point to pull it off',
    path: 'Path: click a line to insert a point · drag ◇ to bend · double-click ◇ to straighten · box handles scale (⇧ keeps proportions, ⌥ from the centre, ⌘ frees the size steps) · any copy is editable · Layer chips move it · drag a node to pull it off a shared point',
    select: 'Select: click a point, line, copy or fill · drag a line to move the path · drag empty space to marquee points',
    freehand: 'Freehand: press and drag · release to fit curves · start on an open end on this layer to continue its path · hold ⌥ to trace a line',
    fill: 'Fill: press to preview a closed region · release to colour it · press again to recolour',
    penActive: 'Pen: click to add · click a line to join it there · click a point or clone anchor to connect · click the last point, Esc or ↵ to finish · Space+drag moves the elements',
    addElement: 'Add an element (O rotation, M mirror, T translation), then draw — every stroke is cloned through it in every cell',
    pen: 'Pen: click a point to start or resume a path · click a line to start from a new point on it · click empty space to add a point',
    counts: { point: 'point', path: 'path', element: 'element', clone: 'clone', fill: 'fill', layer: 'layer' },
    saved: ' · saved',
  },
  help: {
    tabSwitch: ' Drawing ↔ Construction · only the active layer responds to the pointer · ',
    escCancel: ' cancels what is in progress, again clears and returns to Select',
    toolSelect: ' select · ',
    toolPen: ' pen · ',
    toolFreehand: ' freehand · ',
    toolFill: ' fill · ',
    toolGridHold: ' grid snap · hold ',
    toolSnapOr: ' or ',
    toolSnapFree: ' for a free point (no snapping to nodes, lines, edges or corners; the grid still applies while G is on)',
    elRotation: ' rotation · ',
    elMirror: ' mirror · ',
    elTranslation: " translation — stacked as a new group on the selected path's binding, and given to new paths",
    elementsIntro: 'Elements: drag to move · mirror knob or ',
    elementsBetween: ' ',
    elementsRest: ' rotates · translation diamond sets the vector · a group applies left to right (a mirror then a half translation is a glide) · a "then" group applies to the source and every clone so far',
    penIntro: 'Pen: click a point to start or resume · click a line on this layer to join it there (the line gets a shared node; on another layer only its position is copied) · click empty space to add · click the start to close · click the last point, ',
    penOr: ' or ',
    penToEnd: ' to end · ',
    penSpace: '+drag moves the elements',
    freehandIntro: 'Freehand: press and drag, release to fit curves · start on an open end on this layer to extend that path · hold ',
    freehandTrace: ' to trace a nearby line on any layer (it is copied, never joined)',
    selectIntro: 'Select: click any copy of a line to select its path there, again to insert a point · drag ◇ to bend, double-click to straighten · marquee points · ',
    selectShift: ' adds · box handles scale / rotate · drop a point on a point to merge them',
    clone: 'Clone: drag its body to move the first element of its first group · drag its anchors to edit the shared point',
    fill: 'Fill: press to preview a closed region, release to colour · fills draw below the lines of their layer; put them on a higher layer to cover lines',
    wheelIntro: 'Wheel pans · ',
    wheelZoom: '+wheel zooms · two fingers pan and pinch · ',
    wheelFit: ' fits · hover a point + ',
    wheelDelete: ' deletes · ',
    wheelUndo: ' undo · ',
    wheelRedo: ' redo',
    grid: 'Grid ',
    ghosts: 'Ghosts ',
    resetView: 'Reset view',
  },
  titles: {
    drawingLayer: 'Drawing layer: paths, points, fills (Tab)',
    constructionLayer: 'Construction layer: elements and lattice (Tab)',
    layerPick: (name: string, i: number, total: number) => `${name} · layer ${i} of ${total} from the bottom · new paths and fills go here`,
    addLayer: 'Add a layer on top and make it active',
    select: 'Select (V)',
    pen: 'Pen (P)',
    freehand: 'Freehand (F)',
    fill: 'Fill (B)',
    grid: 'Snap to the grid when nothing else is near (G). Nodes, lines, edges and corners always snap, with a hint; hold ⌘ or Ctrl for a free point (the grid still applies while G is on)',
    endPath: 'End the current path (Enter / Esc)',
    addToSelection: 'Add to the selection while marquee-selecting (stands in for Shift)',
    addRotation: 'Add a rotation (1/n turn). New paths are cloned through it.',
    addMirror: 'Add a mirror line.',
    addTranslate: 'Add a translation by a fraction of the lattice.',
    elementChip: (isNewPath: boolean) => (isNewPath ? 'Applies to new paths · click to select' : 'Click to select'),
    removeFromBinding: 'Remove this element from the binding',
    startNewGroupWithElement: 'Start the new group with this element',
    putInGroup: 'Put this element in this group (moves it out of another group)',
    cancelNewGroup: 'Cancel the new group',
    addThenGroup: 'Add a group that applies to the source and to every clone so far',
    newPathBinding: 'Give every new path this binding (★ lit = they get it now)',
    removeBinding: 'Remove this binding and its clones',
    startChain: 'Start another binding on this path (independent clones)',
    startNewBindingWithElement: 'Start the new binding with this element',
    cancelNewBinding: 'Cancel the new binding',
    selectCloneElement: "Select the first element of this clone's chain (switches to Construction)",
    selectSourcePath: 'Select the source path in the base cell',
    newGroupedRotation: "New rotation, stacked as a group on this path's binding",
    newGroupedMirror: "New mirror, stacked as a group on this path's binding",
    newGroupedTranslate: "New translation, stacked as a group on this path's binding",
    straighten: 'Straighten every curved segment (double-click a diamond for one)',
    keepProportions: 'Keep proportions while scaling from the box handles (stands in for ⇧)',
    moveToLayer: (name: string) => `Move this path to ${name}`,
    applyElementToNewPaths: 'Clone every new path through this element',
    nFoldRotation: (n: number) => `${n}-fold rotation`,
    rotateMirrorCCW: 'Rotate −15° ([)',
    rotateMirrorCW: 'Rotate +15° (])',
    setTranslationVector: 'Set the translation vector',
    deleteCloneChain: 'Remove this clone chain (⌫)',
    deleteSelection: 'Delete the selection (⌫)',
    moveFillToLayer: (name: string) => `Move this fill to ${name}`,
    weightPx: (w: number) => `${w}px`,
    undo: 'Undo (⌘Z)',
    redo: 'Redo (⇧⌘Z)',
    fitTile: 'Fit the tile (⌘0)',
    exportTile: 'A single tile, clipped to the cell',
    export3x3: 'The 3×3 window around the tile',
    exportWallpaper: 'A rectangular field of columns × rows cells',
    downloadSvg: 'Download the exported SVG',
    exportSvg: 'Export as SVG',
    exportJson: 'Download the document as JSON',
    importJson: 'Load a JSON document',
    newDocument: 'Start a new design',
    shortcutsHelp: 'Shortcuts and settings (?)',
  },
  bar: {
    symbol: { rotate: '↻', mirror: '⟋', translate: '⇢' },
    chainArrow: ' → ',
    chainThen: ' · then ',
    chainEmpty: '(empty)',
    drawing: '✎ Drawing',
    construction: '⟋ Construction',
    addLayer: '+ layer',
    select: '↖ Select',
    pen: '✎ Pen',
    freehand: '〰 Freehand',
    fill: '◐ Fill',
    grid: '⌗ Grid',
    endPath: 'End path',
    addToSelection: 'Add',
    elements: 'Elements',
    addRotation: '+ ↻ Rotation',
    addMirror: '+ ⟋ Mirror',
    addTranslate: '+ ⇢ Translate',
    newPathWarn: ' ⚠',
    filledMeansNewPaths: 'filled = applies to new paths',
    openWarning: '⚠ an element does not close on this lattice',
    lattice: '▱ Lattice',
    latticeInfo: (a: number, b: number, angle: number) => `a ${a} · b ${b} · ${angle}° · drag the pink a / b handles`,
    close: '✕',
    then: 'then',
    addThenGroup: '+ then',
    newPathStar: '★',
    startChain: '+ chain',
    cloneOfPath: (idx: number, chain: string, power: number) => `Clone of path ${idx} via ${chain} · clone ${power}`,
    pathLabel: (idx: number) => `Path ${idx}`,
    selectCloneElement: 'Select its element',
    selectSourcePath: 'Select source path',
    addElementPrompt: 'add an element with O, M or T',
    newRotation: '+ ↻',
    newMirror: '+ ⟋',
    newTranslate: '+ ⇢',
    straighten: 'Straighten',
    keepProportions: 'Proportional',
    layerColon: 'Layer:',
    elementName: { rotate: 'Rotation', mirror: 'Mirror', translate: 'Translation' },
    elementLabel: (name: string, label: string) => `${name} ${label}`,
    applyToNewPaths: 'Apply to new paths',
    oneOverN: (n: number) => `1/${n}`,
    doesNotTile: (n: number) => `⚠ 1/${n} does not tile on this lattice`,
    rotateCCW: '↺',
    rotateCW: '↻',
    translationPreset: { halfA: '½ a', thirdA: '⅓ a', halfB: '½ b', halfAB: '½ a+b' },
    boundIn: (n: number) => `· in ${n} binding${n > 1 ? 's' : ''}`,
    noPathsYet: '· no paths yet',
    instancesDelete: (n: number) => `${n} instances · Delete removes their paths`,
    fillPickColour: 'Fill · pick a colour in the palette',
    unlink: 'Unlink',
    delete: 'Delete',
    clonesLabel: (n: number, open: boolean) => `${n} clone${n === 1 ? '' : 's'}${open ? ' ⚠' : ''}:`,
    palette: { fill: 'Fill', path: 'Path', stroke: 'Stroke' },
    columns: 'Columns ',
    rows: ' Rows ',
    errorMsg: (msg: string) => `⚠ ${msg}`,
    downloadSvg: 'Download SVG',
    exportSvgBtn: 'Export SVG',
    exportJsonBtn: 'Export JSON',
    importJsonBtn: 'Import JSON',
    newBtn: 'New',
    tile: 'Tile',
    grid3x3: '3×3',
    wallpaper: 'Wallpaper',
    shortcutsIcon: '?',
    undoIcon: '↶',
    redoIcon: '↷',
    importNotUnderstood: 'That file is not a Tessellator document this version understands.',
    replaceDesign: 'Replace the current design?',
    discardDesign: 'Discard the current design?',
  },
} as const;
